// This file is generated by internationalization_builder.dart
// Do not edit this file
import 'package:nodeflow/i18n/internationalization.dart';

class I18n {
  static final Intl empty = Intl('');
  static Intl get hello_world =>  Intl.get('hello.world');
  static Intl get dashboard_project =>  Intl.get('dashboard.project');
  static Intl get dashboard_project_overview =>  Intl.get('dashboard.project.overview');
  static Intl get dashboard_project_projects =>  Intl.get('dashboard.project.projects');
  static Intl get dashboard_account =>  Intl.get('dashboard.account');
  static Intl get dashboard_account_billing =>  Intl.get('dashboard.account.billing');
  static Intl get dashboard_account_settings =>  Intl.get('dashboard.account.settings');
  static Intl get dashboard_account_logout =>  Intl.get('dashboard.account.logout');
  static Intl get dashboard_search =>  Intl.get('dashboard.search');
  static Intl get menubar_file =>  Intl.get('menubar.file');
  static Intl get menubar_file_new =>  Intl.get('menubar.file.new');
  static Intl get menubar_file_import =>  Intl.get('menubar.file.import');
  static Intl get menubar_file_history =>  Intl.get('menubar.file.history');
  static Intl get menubar_file_settings =>  Intl.get('menubar.file.settings');
  static Intl get menubar_file_closeproject =>  Intl.get('menubar.file.closeproject');
  static Intl get menubar_edit =>  Intl.get('menubar.edit');
  static Intl get menubar_edit_undo =>  Intl.get('menubar.edit.undo');
  static Intl get menubar_edit_redo =>  Intl.get('menubar.edit.redo');
  static Intl get menubar_edit_cut =>  Intl.get('menubar.edit.cut');
  static Intl get menubar_edit_copy =>  Intl.get('menubar.edit.copy');
  static Intl get menubar_edit_paste =>  Intl.get('menubar.edit.paste');
  static Intl get menubar_edit_delete =>  Intl.get('menubar.edit.delete');
  static Intl get menubar_view =>  Intl.get('menubar.view');
  static Intl get menubar_tools =>  Intl.get('menubar.tools');
  static Intl get menubar_help =>  Intl.get('menubar.help');
  static Intl get quickaccess_search =>  Intl.get('quickaccess.search');
  static Intl get tooltip_quickaccess_search =>  Intl.get('tooltip.quickaccess.search');
  static Intl get quickaccess_run =>  Intl.get('quickaccess.run');
  static Intl get tooltip_quickaccess_run =>  Intl.get('tooltip.quickaccess.run');
  static Intl get quickaccess_deploy =>  Intl.get('quickaccess.deploy');
  static Intl get tooltip_quickaccess_deploy =>  Intl.get('tooltip.quickaccess.deploy');
  static Intl get quickaccess_build_configuration =>  Intl.get('quickaccess.build_configuration');
  static Intl get tooltip_quickaccess_build_configuration =>  Intl.get('tooltip.quickaccess.build_configuration');
  static Intl get project_default_name =>  Intl.get('project.default.name');
  static Intl get sidebar_projectfiles =>  Intl.get('sidebar.projectfiles');
  static Intl get bottombar_console =>  Intl.get('bottombar.console');
  static Intl get bottombar_todo =>  Intl.get('bottombar.todo');
  static Intl get bottombar_problems =>  Intl.get('bottombar.problems');
}
